plugins { id 'com.android.application' }

android {
    namespace 'com.carjam.aerotheme'
    compileSdk 35

    defaultConfig {
        applicationId 'com.carjam.aerotheme'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '0.1.2'
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
